### PR TITLE
remove_final

### PR DESCRIPTION
**Pull request by thewunder**
I needed to fix a bug (which I may do as a separate pull request), and the final keyword made it much harder than it would have been ordinarily.  There is no reason I see to prevent people from extending your classes.

### CODE REVIEW

**Comment by jaspernbrouwer** [comment]
>There is no reason I see to prevent people from extending your classes.

I'd like to turn this one around: I see no reason why people would need to extend the classes. If you need additional behavior you can always compose (instead of inherit).

But I'm not all-seeing 🙂, so what way your use-case where you needed inheritance?

**Comment by thewunder** [comment]
To be honest I'm not exactly sure I understand the root cause of the issue I needed to work around.

Basically sometimes, Swift_Attachment::getBody() will return null, but calling it twice will fix the issue (??)

I would have done the fix by extending the StandardPayloadBuilder if it were possible to do so.  Instead I had to use an event observer.

In general the final keyword is only useful when part of your library is intended to be extended and part isn't.  If you make everything final then it just makes it harder to write classes that implement your interfaces.

**Comment by jaspernbrouwer** [comment]
>Basically sometimes, Swift_Attachment::getBody() will return null, but calling it twice will fix the issue (??)

That's strange indeed! My instincts tell me the source of the issue must be in SwiftMailer itself, because this library only iterates over attachments to build the payload. Nothing fancy there.

I do see why you want a "quickfix" in the payload-builder. Your issue with the `final` keyword can easily be overcome like this:

```php
<?php

use SwiftSparkPost\PayloadBuilder;
use Swift_Mime_Message;

final class MySpecialPayloadBuilder implements PayloadBuilder
{
    private $wrappedPayloadBuilder;

    public function __construct(PayloadBuilder $wrappedPayloadBuilder)
    {
        $this->wrappedPayloadBuilder = $wrappedPayloadBuilder;
    }

    public function buildPayload(Swift_Mime_Message $message)
    {
        $payload = $this->wrappedPayloadBuilder->buildPayload($message);

        // My special stuff

        return $payload;
    }
}
```

This will get you the same result as inheritance, while letting me keep the public api small (which means I can change things without creating BC breaks more easily).

**Comment by thewunder** [comment]
True, it can be done with composition.  By why limit the user's options?  If you look at most well known  libraries, final is used very sparingly.  Anyway totally up to you.

**Comment by jaspernbrouwer** [comment]
Yes, we'll agree to disagree 🙂 IMHO having more options (just for the sake of having more options) makes things more complex and harder to understand. 

I can imagine that a lot of the private methods in `StandardPayloadBuilder` could be extracted into an abstract class, so they are reusable. I don't get the impression that would solve your immediate issue, but it might make other cases easier to do.

Thanks for the effort though, and your other PR (you're totally right on that one)!

**Pull request closed without merging**
